unique_ids:
  assets:
    standard-page.html: MJCEXUPST6D7RAGLXKZX6VFQ6HP23E54
    theme.css: WBDI5LBBFR3ZHT3N6PTBIE5V3HX76FAZ
  forms:
    Form1: XYN7IAPX36XLUA6LY7LU6KODGPUBSJU4
  modules: {}
  scripts: {}
  server_modules: {}
